formats:
  - oas3
extends:
  - 'spectral:oas'
rules:
  info-matches-stoplight:
    description: This is an example rule
    message: Info must contain Stoplight
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: pattern
      functionOptions:
        match: Stoplight
  strings-have-max:
    description: String properties should define a maximum length
    message: String properties should define a maximum length
    given: "properties.[?(@.type==string)]"
    recommended: true
    type: style
    then:
      field: maxLength
      function: falsey

      