openapi: 3.0.0
info:
  title: Listing REST APIs
  version: '1.0'
  description: ''
servers:
  - url: 'https://prod.apigateway.co/products/listings/listListings'
    description: Production
  - url: 'https://demo.apigateway.co/products/listings/listListings'
    description: Demo
  - url: '{local}/products/listings/listListings'
    description: Local
  - url: 'http://localhost:11001/products/listings/listListings'
    description: Localhost
paths:
  /listListings:
    get:
      summary: List Business Entity Listings
      operationId: list-businessListings
      tags:
        - Business Entity Listings
      security:
        - OAuth2:
            - business
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`
        Gets a list of listings for a business entity
      parameters:
        - schema:
            type: string
            example: Bearer <Access Token>
            pattern: ^Bearer\s\S+
          in: header
          name: Authorization
          description: A Bearer access token to identify the user the app is acting on behalf of. See the Authorization guide for details.
          required: true
        - schema:
            type: string
          in: query
          name: 'filter[businessLocation.id]'
          description: Return listings for the specified business entity
          required: true
        - schema:
            type: string
          in: header
          name: Accept-Language
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/listListings'
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        format: uri
                      first:
                        type: string
                        description: Provides a link back to the first page of results
                        format: uri
                      next:
                        type: string
                        description: The URI at which the next batch of listings can be gotten from
                        format: uri
    options:
      operationId: options-businessEntityListings
      summary: List valid HTTP verbs for /businessEntityListings
      description: 'Used solely for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) the OPTIONS request returns the list of possible HTTP methods and other headers that browsers use to protect user''s security. You should not call this operation directly. '
      responses:
        '204':
          description: No Content
        '403':
          description: User Cannot Access Entity
        '404':
          description: Business Not Found
        '406':
          description: No Listing Product Active
      tags:
        - Options
        - Business Entity Listings
    parameters: []
components:
  schemas:
    businessLocationReviews:
      title: Business Entity Listings
      type: object
      x-lifecycle:
        status: trustedTester
      description: |-
        [Status](https://developers.vendasta.com/platform/ZG9jOjEwMTU2NTYy-versioning): `Trusted Tester`
        Gets a list of listings for a business entity
      x-tags:
        - Business Entity Listings
      properties:
        id:
          name:
            description: Public facing name of the source
            type: string
            example: HotFrog
        type:
          type: string
          default: listings
          enum:
            - listings
        attributes:
          type: object
          icon:
            description: Link to icon provided by Vendasta’s media service
            type: string
            format: uri
            example: //www.cdnstyles.com/static/images/icon32/sourceId-10090.png
          popularity:
            description: Popularity of the source relative to other sources
            type: number
          sourceTypeCode:
            description: Type of source, business directory, app (Snapchat), GPS app, etc.
            type: string
            example: BUSINESS_DIRECTORY
          syncStatusCode:
            description: The publishing status provided by the sources. Some sources provide confirmation that your data has been published (synced) other sources only provide confirmation that your data has been received (submitted)
            type: string
            example: SYNCED
          listingScore:
            description: A score based on the status of your online source
            type: number
          maximumlistingScore:
            description: The maximum score this source can attain
            type: number
          url:
            description: The online listing
            format: uri
            type: string
          syncingError:
            type: array
            description: Any errors reported while publishing your information to the source
            items:
              type: object
              properties:
                errorCode:
                  description: Use this to determine why a publishing listing information to a source has failed
                  type: string
                  example: STREET_ADDRESS, CATEGORIES
                errorDetails:
                  description: Human readable details about the error
                  type: string
          syncingWarning:
            description: Any warnings reported while publishing your information to the source
            type: array
            items:
              type: object
              properties:
                warningCode:
                  description: Use this to determine why parts of the published information are different or there are possible conflicts with other listings
                  type: string
                  example: DOES_NOT_SUPPORT_SERVICE_AREA_BUSINESS, CLAIMED_BY_OTHERS
                warningDetails:
                  description: Human readable details about the warning
                  type: string
          updatedAt:
            description: The last time this source’s listing was checked by Vendasta’s independent listing verification system
            format: date
            type: string
          address:
            description: The address information displayed in the online listing
            type: object
            properties:
             streetAddress:
               description:  The physical address of the entity, if it has one. Vendasta’s platform supports multiple address lines but currently those are combined into a single street address in our listing verification system.
               type: string
             city:
              description: City displayed on the listing itself
              type: string
             regionCode:
               description: TODO
               type: string
             countryCode:
               description: TODO
               type: string
             postalCode:
               description: TODO
               type: string
          matches:
            description: Indicates which parts of your online listing are accurate based on Vendasta’s independent listing verification system
            type: object
            properties:
              streetAddress:
                type: boolean
              city:
                type: boolean
              regionCode:
                type: boolean
              countryCode:
                type: boolean
              postalCode:
                type: boolean
          accuracyStatusCode:
            description: Indicates if reporting is available. If available indicates if the listing was found. If the listing was found indicates if all the data is correct on the listing.
            type: string
            example: NOT_AVAILABLE, NOT_FOUND, INACCURATE, ACCURATE
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso-api-demo.apigateway.co/oauth2/auth'
          tokenUrl: 'https://sso-api-demo.apigateway.co/oauth2/token'
          refreshUrl: ''
          scopes:
            reputation: Access to the Listing Builder REST API